insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (1, 25000, 'Saltillo Centro', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (2, 25010, 'Vista Hermosa', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (3, 25010, 'La Fuente', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (4, 25010, 'Privada la Misión', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (5, 25010, 'Privada la Campana', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (6, 25010, 'Nuevo Saltillo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (7, 25010, 'Privada de San Javier', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (8, 25010, 'Solidaridad', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (9, 25010, 'Parajes de la Sierra', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (10, 25013, '15 de Septiembre', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (11, 25013, 'Villa Morelos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (12, 25013, 'Milenio', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (13, 25013, 'El Monte del Sinaí', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (14, 25013, 'Cordillera', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (15, 25013, 'La Cascada', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (16, 25013, 'Ampliación Morelos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (17, 25013, 'Amistad', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (18, 25013, 'Morelos Nueva Creación', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (19, 25013, 'Balcones de Morelos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (20, 25013, 'Valle de Morelos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (21, 25013, 'Parque Industrial Amistad', 'Zona industrial');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (22, 25013, 'Privada Morelos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (23, 25013, 'Colibrí', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (24, 25014, '10 de Abril', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (25, 25014, 'San Pedro de los Pinos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (26, 25014, 'Cecilia Ocelli de Salinas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (27, 25015, 'Fundadores', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (28, 25015, 'El Pedregal', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (29, 25015, 'Fuentes del Pedregal', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (30, 25015, 'Edgar Puente', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (31, 25015, 'Nueva Vida', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (32, 25015, 'Villa de Santiago', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (33, 25015, 'Lomas del Pedregal', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (34, 25015, 'Lomas de Zapaliname', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (35, 25015, 'Valle de las Aves', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (36, 25015, 'Salomón Abedrop', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (37, 25015, 'Lomas de San Francisco', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (38, 25015, 'Nueva Independencia', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (39, 25015, 'Nuevo Progreso', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (40, 25015, 'Introductores de Ganado', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (41, 25016, 'Ignacio Zaragoza', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (42, 25016, 'Residencial los Rosales', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (43, 25016, 'Colinas de Santiago', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (44, 25016, 'Popular Loma Blanca', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (45, 25016, 'Sierra Alta Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (46, 25016, 'Prados de San José', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (47, 25016, 'Tres Vientos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (48, 25016, 'Valle de los Almendros', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (49, 25016, 'Privada Villas de San José', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (50, 25016, 'Ciudad Mirasierra', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (51, 25016, 'Lomas del Bosque', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (52, 25016, 'Puerta del Oriente', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (53, 25016, 'Privadas la Torre', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (54, 25016, 'Privada los Magueyes', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (55, 25016, 'Loma Linda', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (56, 25016, 'Gaspar Valdez', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (57, 25016, 'Real del Sol', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (58, 25016, 'Recreativo Sección 38', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (59, 25016, 'Francisco I Madero Rústico', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (60, 25016, 'Nuevo Mirasierra', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (61, 25016, 'Privadas Sierras del Oriente', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (62, 25016, 'Sierra Blanca', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (63, 25016, 'Misión Cerritos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (64, 25016, 'Santa Lucía', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (65, 25017, 'Ampliación Valle de Morelos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (66, 25017, 'Morelos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (67, 25017, 'Ampliación Morelos Segundo Sector', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (68, 25019, 'Conquistadores', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (69, 25019, 'Privada Nogal I', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (70, 25019, 'La Nogalera', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (71, 25019, 'El Cerrito', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (72, 25019, 'Nueva Tlaxcala', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (73, 25019, 'Rubén Jaramillo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (74, 25019, 'Tierra y Libertad', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (75, 25019, 'La Morita', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (76, 25019, 'Nueva Imagen', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (77, 25019, 'El Ejido', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (78, 25019, 'El Nogalar', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (79, 25019, 'Nuevo Amanecer', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (80, 25019, 'Las Candelarias', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (81, 25019, 'Postal Cerritos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (82, 25019, 'San José', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (83, 25019, 'Los Lirios', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (84, 25019, 'Candelarias Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (85, 25019, 'Santa María', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (86, 25019, 'Las Maravillas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (87, 25019, 'Villa Fundadores', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (88, 25020, 'Provivienda', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (89, 25020, 'San Ramón', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (90, 25020, 'Urdiñola', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (91, 25020, 'Zapaliname', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (92, 25020, 'Indio', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (93, 25020, 'San Esteban', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (94, 25020, 'Valle de San Ramón', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (95, 25022, 'Centro Metropolitano', 'Equipamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (96, 25022, 'Parque las Maravillas', 'Equipamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (97, 25023, 'Universidad Pueblo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (98, 25023, 'Montevista', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (99, 25023, 'Cantabria', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (100, 25023, 'La Palma', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (101, 25023, 'El Paraíso', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (102, 25023, 'San Vicente', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (103, 25023, 'Arboledas Popular', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (104, 25023, 'Loma Bonita', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (105, 25023, 'Valle de las Palmas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (106, 25023, 'Valle de Santa Elena', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (107, 25023, 'La Rosaleda', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (108, 25030, 'Agua Azul', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (109, 25030, 'Arcos de Belén', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (110, 25030, 'González Cepeda', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (111, 25030, 'Loma de Santa Anita', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (112, 25034, 'Magisterio Sección 38', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (113, 25034, 'Santa Anita', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (114, 25034, 'Esther Santos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (115, 25036, 'Huertas de Venancio', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (116, 25038, 'Condesa', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (117, 25038, 'Ampliación San Ramón', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (118, 25039, 'Deimos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (119, 25040, 'Ojo de Agua', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (120, 25040, 'San Lorenzo', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (121, 25040, 'Barrio Santa Anita', 'Barrio');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (122, 25040, 'Viramontes', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (123, 25040, 'Balcones de Bellavista', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (124, 25043, 'Héroes de Chapultepec', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (125, 25045, 'Zapateros', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (126, 25045, 'Portal de Santiago', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (127, 25047, 'Los Álamos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (128, 25048, 'Burócratas del Estado', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (129, 25048, 'Lomas de Chapultepec', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (130, 25049, 'Santa María', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (131, 25049, 'Simón Bolívar', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (132, 25049, 'Águila de Oro', 'Barrio');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (133, 25050, 'Benito Juárez', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (134, 25050, 'María del Carmen Cabello', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (135, 25050, 'Centenario', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (136, 25050, 'Chapultepec', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (137, 25050, 'La Madrid', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (138, 25050, 'Rosa María Gutiérrez', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (139, 25056, 'El Salvador', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (140, 25057, 'El Volcán', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (141, 25057, 'Los Nogales', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (142, 25057, 'Jesús Cabello', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (143, 25057, 'Lomas de San Javier', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (144, 25057, 'Colinas de San Francisco', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (145, 25057, 'La Herradura', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (146, 25057, 'Los Nogales II', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (147, 25057, 'Parajes de Oriente', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (148, 25060, 'Bellavista', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (149, 25060, 'Francisco I Madero', 'Unidad habitacional');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (150, 25060, 'Segovia Gil', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (151, 25060, 'Lázaro Cárdenas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (152, 25060, 'Los Arcos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (153, 25060, 'Lucio Blanco', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (154, 25060, 'Miravalle', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (155, 25060, 'San Lorenzo Oriente', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (156, 25060, 'Luis Donaldo Colosio', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (157, 25060, 'Acueducto', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (158, 25060, 'La Central', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (159, 25060, 'Bellavista Mesa de Arizpe', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (160, 25065, 'Huertas de San Lorenzo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (161, 25065, '15 de Abril', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (162, 25065, 'Cerrada San Lorenzo', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (163, 25065, 'Jesús Garcia Corona', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (164, 25065, 'Patria Libre', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (165, 25065, 'Nueva Reforma', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (166, 25067, 'Quinta Valle', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (167, 25068, 'Quinta Esmeralda', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (168, 25069, 'Villa Universidad', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (169, 25069, 'Valle de Lourdes', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (170, 25069, 'Las Haciendas', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (171, 25070, 'Landin', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (172, 25070, 'Lomas de Guadalupe', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (173, 25070, 'Lourdes', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (174, 25070, 'Privada Obregón Sur', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (175, 25070, 'Balcones de Landin', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (176, 25070, 'Lomas de Landín', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (177, 25070, 'Privada Rincón de Salazar', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (178, 25075, '26 de Marzo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (179, 25075, 'Ferrocarrilero 7 de Noviembre', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (180, 25076, 'Buenos Aires', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (181, 25077, 'Los Balcones de Buenavista', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (182, 25077, 'Valle Alto', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (183, 25080, 'Eulalio Gutiérrez Treviño', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (184, 25080, 'Girasol', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (185, 25080, 'Parques de la Cañada', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (186, 25080, 'Froylán Mier Narro', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (187, 25080, 'Los Periodistas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (188, 25083, 'El Refugio la Soledad', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (189, 25083, 'Hacienda del Refugio', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (190, 25083, 'Parque Industrial la Angostura', 'Zona industrial');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (191, 25083, 'Sierra del Sur', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (192, 25083, 'Hacienda el Mimbre', 'Equipamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (193, 25083, 'Amistad Alianzas', 'Zona industrial');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (194, 25084, 'Lomas del Sur', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (195, 25084, 'Valle de San Lorenzo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (196, 25084, 'La Estrella', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (197, 25084, '69 Batallón de Infantería', 'Zona militar');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (198, 25084, 'Las Teresitas', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (199, 25084, 'Niños Héroes', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (200, 25084, 'Lomas del Refugio', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (201, 25084, 'Las Rosas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (202, 25084, 'Colinas de San Lorenzo', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (203, 25084, 'Parajes de Santa Elena', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (204, 25084, 'Hacienda las Isabeles', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (205, 25084, 'Villas de la Angostura', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (206, 25084, 'Ampliación la Estrella', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (207, 25084, 'Nuevo Teresitas', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (208, 25085, 'Guadalupe Victoria', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (209, 25085, 'Rincón de Foret', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (210, 25085, 'Foret', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (211, 25085, 'Genaro Vázquez Rojas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (212, 25085, 'El Latifundio', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (213, 25086, 'Burócratas Municipales', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (214, 25086, 'Ampliación 26 de Marzo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (215, 25086, 'Privada Colombia', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (216, 25087, 'Ampliación Girasol', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (217, 25088, 'Hacienda Narro', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (218, 25088, 'Villas de San Francisco', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (219, 25088, 'Viñedos el Álamo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (220, 25088, 'Agua Nueva', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (221, 25088, 'Ricardo Flores Magón', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (222, 25088, 'Nueva Jerusalén', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (223, 25088, 'El Álamo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (224, 25088, '23 de Noviembre', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (225, 25088, 'El Progreso', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (226, 25088, 'María del Carmen Cavazos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (227, 25088, 'Australia', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (228, 25088, '12 de Octubre', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (229, 25088, 'La Esperanza', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (230, 25088, 'San Juanita', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (231, 25088, 'El Álamo II', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (232, 25088, 'Mario Ortiz Rodríguez', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (233, 25088, 'El Álamo', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (234, 25090, 'Lomas de Lourdes', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (235, 25090, 'Valle Dorado', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (236, 25092, 'Lomas de Santa Cruz', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (237, 25092, 'Humberto Dávila Esquivel', 'Unidad habitacional');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (238, 25092, 'Villas de San Lorenzo', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (239, 25092, 'Las Huertas de Lourdes', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (240, 25093, 'Santa Mónica', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (241, 25093, 'Los Buitres', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (242, 25093, 'Colinas del Sur', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (243, 25093, '10 de Mayo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (244, 25093, 'Hacienda el Cortijo', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (245, 25093, 'Mesa de Lourdes', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (246, 25093, 'Portal del Sur', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (247, 25093, 'Ampliación Colinas del Sur', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (248, 25093, 'Los Buitres II', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (249, 25094, 'Monteverde Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (250, 25094, 'Paseo de la Estrella', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (251, 25094, 'Privadas la Estrella', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (252, 25094, 'Bosques de las Lomas Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (253, 25094, 'Cumbres Vista Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (254, 25094, 'Portal de las Lomas', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (255, 25096, 'Miguel Hidalgo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (256, 25096, 'Vistas de Peña', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (257, 25096, 'Vistas de Peña Sur', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (258, 25096, 'María de León', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (259, 25096, 'Federico Berrueto Ramón Popular', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (260, 25096, 'Federico Berrueto Ramón', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (261, 25096, 'Lomas Verdes', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (262, 25097, 'Vicente Guerrero', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (263, 25097, 'Las Rosas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (264, 25100, 'Nazario S Ortiz Garza', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (265, 25100, 'Industrial Valle de Saltillo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (266, 25100, 'Hacienda San Rafael', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (267, 25100, 'Omega', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (268, 25100, 'La Purísima', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (269, 25107, 'Asturias', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (270, 25107, 'Portal de Asturias', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (271, 25107, 'Rincón de Asturias', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (272, 25107, 'Valle Verde Sector II', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (273, 25107, 'Nuevo México', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (274, 25110, 'Ciudad las Torres', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (275, 25110, 'Las Torres', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (276, 25110, 'Nuevo Atardecer', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (277, 25110, 'Portales', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (278, 25110, 'Evaristo Pérez Arreola', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (279, 25110, 'Valle de las Torres', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (280, 25110, 'Flora Ortega', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (281, 25110, 'El Rodeo', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (282, 25110, 'Valle Azteca', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (283, 25110, 'La Florencia', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (284, 25110, 'Valle de las Torres II', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (285, 25110, 'Balcones de las Torres', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (286, 25110, 'Valle Satélite', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (287, 25113, 'Satélite Sur', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (288, 25114, 'Parque Industrial las Torres', 'Zona industrial');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (289, 25115, 'Satélite Norte', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (290, 25115, 'Santorini', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (291, 25115, 'Saltillo 2000', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (292, 25115, 'Portal de los Agaves', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (293, 25115, 'Portal del Quijote', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (294, 25115, 'San José de Flores', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (295, 25115, 'Portal del Pedregal', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (296, 25116, 'Valencia', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (297, 25116, 'Andalucía', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (298, 25116, 'San Isidro', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (299, 25117, 'Ankara Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (300, 25117, 'Triana', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (301, 25117, 'Privada Lantana', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (302, 25117, 'Privada Luxor', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (303, 25117, 'Villas Castellana', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (304, 25117, 'Real Ankara', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (305, 25117, 'El Rocal Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (306, 25117, 'Santa Fe', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (307, 25120, 'Francisco I Madero', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (308, 25123, 'Pedregal de los Santos Sur', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (309, 25123, 'Ejido Padres Santos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (310, 25123, 'La Magueyada', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (311, 25123, 'Ejido la Vega', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (312, 25124, 'Las Cumbres', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (313, 25124, 'Rancho Flores', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (314, 25124, 'Loma Dorada', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (315, 25124, 'Ocho de Enero', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (316, 25124, 'Ignacio Allende', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (317, 25124, 'Residencial Rincón de San Vicente', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (318, 25125, 'Roma', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (319, 25125, 'Adolfo López Mateos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (320, 25128, 'Josefa Ortiz de Domínguez', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (321, 25128, 'Puerto de Flores', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (322, 25128, '1° de Mayo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (323, 25130, 'Anáhuac', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (324, 25130, 'Antonio Cárdenas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (325, 25130, 'Gustavo Espinosa Mireles', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (326, 25130, 'Isabel Amalia Dávila', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (327, 25137, 'Pueblo Insurgentes', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (328, 25137, 'Paraíso', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (329, 25137, 'Hacienda la Magueyada', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (330, 25138, 'González Norte', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (331, 25138, 'Altaria Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (332, 25138, 'Emilio Carranza', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (333, 25138, 'Valle Universidad', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (334, 25138, 'Privada Guadalupe', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (335, 25138, 'Cerrada Guadalupe', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (336, 25140, 'Cerro del Pueblo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (337, 25140, 'Ejército Constitucionalista', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (338, 25140, 'Independencia', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (339, 25140, 'Panteones', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (340, 25140, 'Hacienda San Pablo', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (341, 25140, 'Las Mitras', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (342, 25140, 'Sierras del Poniente', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (343, 25140, 'Azteca', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (344, 25140, 'Valle de San Antonio', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (345, 25140, 'Campo Verde', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (346, 25140, 'Obrera', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (347, 25140, 'María Luisa', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (348, 25140, 'Antonio Cárdenas Sur', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (349, 25146, 'Oscar Flores Tapia', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (350, 25147, 'Loma Alta', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (351, 25150, 'Alfredo V Bonfil', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (352, 25150, 'Mirador', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (353, 25150, 'Universo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (354, 25150, 'Valle de las Flores Popular', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (355, 25154, 'Ejido la Minita', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (356, 25155, 'Los Balcones', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (357, 25155, 'Puerto de la Virgen', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (358, 25155, 'Rincón de Guadalupe', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (359, 25155, 'Valle del Poniente', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (360, 25155, 'Las Margaritas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (361, 25156, 'Francisco Villa', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (362, 25157, 'Los Fresnos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (363, 25157, 'Valle Escondido', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (364, 25157, 'Valle Escondido Sur', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (365, 25157, 'Venustiano Carranza', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (366, 25160, 'Alameda', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (367, 25160, 'Del Valle', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (368, 25160, 'Zamora', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (369, 25160, 'Bordo Ferrocarril', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (370, 25160, 'Huerta los Pilares', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (371, 25160, 'Privada Quinta Narro', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (372, 25167, 'Guayulera Tierra y Esperanza', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (373, 25167, 'Ampliación Pacheco', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (374, 25167, 'Providencia', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (375, 25167, 'Privada Coahuila y Zacatecas', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (376, 25168, 'Privada Beta Centauro', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (377, 25169, 'Brisas del Valle', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (378, 25169, 'Unidad Modelo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (379, 25170, 'El Bosque', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (380, 25170, 'La Minita', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (381, 25170, 'La Peñita', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (382, 25179, 'Los Cuernitos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (383, 25180, 'Chamizal', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (384, 25180, 'Guayulera', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (385, 25180, 'Ruiz Cortines', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (386, 25186, 'San Miguel', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (387, 25186, 'El Edén', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (388, 25188, 'Río Verde', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (389, 25190, '5 de Mayo', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (390, 25190, 'El Tanquecito', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (391, 25190, 'Providencia', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (392, 25193, 'Rincón de los Pastores', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (393, 25193, 'Héroes de Nacozari', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (394, 25194, 'Ignacio Zaragoza Popular', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (395, 25194, 'Valle Verde', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (396, 25194, 'Julieta Pérez', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (397, 25194, 'Diana Laura Riojas de Colosio', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (398, 25194, 'Los Berros', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (399, 25195, 'Patria Nueva', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (400, 25196, 'Santa Teresa', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (401, 25197, 'Ladrilleros', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (402, 25197, 'Los Rosarios Popular', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (403, 25197, 'La Esmeralda', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (404, 25197, 'La Joyita', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (405, 25197, 'El Morillo', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (406, 25197, 'La Romita', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (407, 25198, 'Los Pinos', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (408, 25199, 'San Isidro', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (409, 25200, 'Las Huertas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (410, 25200, 'Los Rodríguez', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (411, 25200, 'Arboledas Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (412, 25200, 'Los Zendejos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (413, 25200, 'La Rioja Terrán', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (414, 25200, 'La Rioja', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (415, 25200, 'Villanatura', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (416, 25200, 'Villas de Sayavedra', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (417, 25200, 'Jardines de Versalles', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (418, 25200, 'Las Cabañas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (419, 25200, 'Villas del Ranchito', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (420, 25200, 'Rincón de Sayavedra', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (421, 25203, 'Las Magnolias', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (422, 25203, 'Jacarandas Jardín', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (423, 25203, 'Nuestra Señora de Fátima', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (424, 25204, 'Habita', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (425, 25204, 'Los González', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (426, 25204, 'San Alberto', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (427, 25204, 'Residencial San Patricio', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (428, 25204, 'El Portal', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (429, 25204, 'Privada Emilio Rodríguez', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (430, 25204, 'La Cantera Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (431, 25204, 'Habita II', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (432, 25204, 'La Joya', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (433, 25204, 'Albareda Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (434, 25204, 'Saqqara', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (435, 25204, 'Los Pinos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (436, 25204, 'Valle Real', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (437, 25204, 'Villa Toscana', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (438, 25204, 'Villas de San Miguel', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (439, 25204, 'Los Siller', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (440, 25204, 'San Patricio Plus', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (441, 25204, 'San José Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (442, 25204, 'Hacienda San Jerónimo', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (443, 25204, 'Villas de Aranjuez', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (444, 25206, 'Jardines Coloniales', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (445, 25206, 'Las Quintas', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (446, 25206, 'Privada Coloniales', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (447, 25207, 'Los Algodones', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (448, 25207, 'Country Club Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (449, 25207, 'Puerta del Sol', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (450, 25207, 'El Suspiro', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (451, 25207, 'Valle Hermoso', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (452, 25207, 'Los Cedros Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (453, 25207, 'Albatros Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (454, 25208, 'Jardines del Campestre Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (455, 25208, 'Loma Blanca', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (456, 25208, 'Los Bosques', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (457, 25208, 'Vivennto Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (458, 25208, 'Nogalar del Campestre', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (459, 25208, 'Campestre Capellanía', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (460, 25209, 'Los Valdez', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (461, 25209, 'Villa San Juan', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (462, 25209, 'Rincón de los Adobes', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (463, 25209, 'Rincón de Alcántara', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (464, 25209, 'Sorrento', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (465, 25209, 'Lomas de Peña', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (466, 25209, 'San Juan Bautista', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (467, 25209, 'Torrealta Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (468, 25209, 'Rincón de los Encinos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (469, 25209, 'Punta Bosque', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (470, 25209, 'La Poza', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (471, 25209, 'Peña Alta', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (472, 25209, 'Campestre la Poza', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (473, 25209, 'El Campanario', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (474, 25209, 'Las Misiones', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (475, 25209, 'Quinta Real', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (476, 25209, 'Los Arrayanes', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (477, 25209, 'Santa Rosa Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (478, 25209, 'Villa del Carmen Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (479, 25210, 'Hacienda de Peña', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (480, 25210, 'Las Brisas', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (481, 25210, 'Los Álamos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (482, 25210, 'Nueva España', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (483, 25210, 'Rancho de Peña', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (484, 25210, 'Rivera del Valle', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (485, 25210, 'La Noria', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (486, 25210, 'Villa Vergel Residencial', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (487, 25210, 'Privadas de Santiago', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (488, 25210, 'Valle las Palmas', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (489, 25210, 'Oasis', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (490, 25215, 'Valle San Agustín', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (491, 25220, 'Río Bravo', 'Unidad habitacional');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (492, 25220, 'Virreyes Obrera', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (493, 25220, 'Virreyes Popular', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (494, 25220, 'Residencial los Encinos', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (495, 25220, 'Zona Industrial', 'Zona industrial');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (496, 25225, 'Virreyes Colonial', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (497, 25225, 'Brisas Poniente', 'Fraccionamiento');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (498, 25225, 'Virreyes Industrial', 'Zona industrial');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (499, 25230, 'Villa Olímpica', 'Colonia');
insert into colonia (id_colonia, codigoPostal, asentamiento, tipo_asentamiento) values (500, 25230, 'FOVISSSTE Virreyes', 'Unidad habitacional');



